#!/bin/bash
# Unified bridge deployment script.
# Usage: deploy/deploy-bridge.sh <binary> <user@host> [hub|direct]
#
# hub:    bridge connects outbound to central server (default)
# direct: bridge listens on QUIC for inbound MCP connections
#
# This script handles:
# - Binary upload to /usr/local/bin/rmux-bridge
# - CA cert + TLS cert deployment to /etc/yunying/
# - bridge.env generation
# - Systemd unit creation
# - Cleanup of old /opt/yunying/ artifacts
set -euo pipefail

BINARY="${1:?Usage: $0 <binary> <user@host> [hub|direct]}"
REMOTE="${2:?Usage: $0 <binary> <user@host> [hub|direct]}"
MODE="${3:-hub}"
CERTS_DIR="${CERTS_DIR:-certs}"

HOST_IP=$(echo "$REMOTE" | sed 's/.*@//' | cut -d: -f1)

echo "=== Deploying rmux-bridge to $REMOTE (mode: $MODE) ==="

# 1. Install rmux if needed
ssh "$REMOTE" 'command -v rmux >/dev/null 2>&1 || curl -fsSL https://rmux.io/install.sh | sh'

# 2. Write profile.d for RMUX_TMPDIR
ssh "$REMOTE" "echo 'export RMUX_TMPDIR=\$HOME/.rmux' | sudo tee /etc/profile.d/yunying.sh > /dev/null" 2>/dev/null || true

# 3. Create /etc/yunying directory
ssh "$REMOTE" "sudo mkdir -p /etc/yunying"

# 4. Upload binary
scp "$BINARY" "$REMOTE:/tmp/rmux-bridge.new"
ssh "$REMOTE" "sudo mv /tmp/rmux-bridge.new /usr/local/bin/rmux-bridge && sudo chmod 755 /usr/local/bin/rmux-bridge"

# 5. Upload CA cert
if [ -f "$CERTS_DIR/ca.crt" ]; then
    scp "$CERTS_DIR/ca.crt" "$REMOTE:/tmp/ca.crt"
    ssh "$REMOTE" "sudo mv /tmp/ca.crt /etc/yunying/ca.crt && sudo chmod 644 /etc/yunying/ca.crt"
fi

# 6. Detect rmux socket
RMUX_SOCK=$(ssh "$REMOTE" "for d in /run/rmux \$HOME/.rmux /tmp; do s=\$(ls \$d/rmux-*/default 2>/dev/null | head -1); [ -n \"\$s\" ] && echo \$s && break; done; [ -z \"\$s\" ] && echo '/root/.rmux/rmux-0/default'")
echo "Detected rmux socket: $RMUX_SOCK"

# 7. Generate bridge.env
BRIDGE_ENV="# yunying bridge configuration
# Generated by deploy/deploy-bridge.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Authentication
BRIDGE_AUTH_TOKEN=${BRIDGE_TOKEN:?Set BRIDGE_TOKEN env var}

# Rmux socket
RMUX_SOCKET=$RMUX_SOCK

# Recording
RECORDING_ENABLED=true
RECORDING_DIR=/opt/agent-ops/recordings
BRIDGE_AUDIT_DB=/opt/agent-ops/bridge_events.db
"

if [ "$MODE" = "hub" ]; then
    SERVER_ADDR="${YUNYING_SERVER_ADDR:-10.220.71.1:9788}"
    BRIDGE_ENV+="
# Hub server connection
YUNYING_SERVER_ADDR=$SERVER_ADDR
YUNYING_CA_CERT=/etc/yunying/ca.crt
"
fi

if [ "$MODE" = "direct" ] || [ "${BOTH_MODES:-0}" = "1" ]; then
    # Upload TLS cert+key for QUIC listener
    HOST_CERT="$CERTS_DIR/${HOST_IP}.crt"
    HOST_KEY="$CERTS_DIR/${HOST_IP}.key"

    if [ -f "$HOST_CERT" ] && [ -f "$HOST_KEY" ]; then
        scp "$HOST_CERT" "$REMOTE:/tmp/bridge.crt"
        scp "$HOST_KEY" "$REMOTE:/tmp/bridge.key"
        ssh "$REMOTE" "sudo mv /tmp/bridge.crt /etc/yunying/bridge.crt && sudo chmod 644 /etc/yunying/bridge.crt"
        ssh "$REMOTE" "sudo mv /tmp/bridge.key /etc/yunying/bridge.key && sudo chmod 600 /etc/yunying/bridge.key"

        BRIDGE_ENV+="
# QUIC listener (direct mode)
QUIC_LISTEN_ADDR=0.0.0.0:9778
BRIDGE_TLS_CERT=/etc/yunying/bridge.crt
BRIDGE_TLS_KEY=/etc/yunying/bridge.key
"
    else
        echo "WARNING: TLS certs not found for $HOST_IP, QUIC listener disabled"
    fi
fi

# Write bridge.env
echo "$BRIDGE_ENV" | ssh "$REMOTE" "sudo tee /etc/yunying/bridge.env > /dev/null && sudo chmod 600 /etc/yunying/bridge.env"

# 8. Write systemd unit
ssh "$REMOTE" "sudo tee /etc/systemd/system/rmux-bridge.service" <<'UNIT_EOF'
[Unit]
Description=yunying Bridge
After=network.target rmux-daemon.service

[Service]
EnvironmentFile=/etc/yunying/bridge.env
ExecStart=/usr/local/bin/rmux-bridge
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT_EOF

# 9. Cleanup old deployment artifacts
ssh "$REMOTE" "sudo rm -f /usr/local/bin/rmux-bridge.new; sudo rm -rf /opt/yunying/" 2>/dev/null || true

# 10. Reload and start
ssh "$REMOTE" "sudo systemctl daemon-reload && sudo systemctl enable --now rmux-bridge"

echo ""
echo "=== Deployment complete ==="
echo "Host:  $REMOTE"
echo "Mode:  $MODE"
echo "Check: ssh $REMOTE systemctl status rmux-bridge"
