[package]
name = "clum-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
anyhow = "1"
rustls = { version = "0.23", default-features = false, features = ["std"] }
rustls-pemfile = "2"
webpki-roots = "1"
quinn = { workspace = true, features = ["rustls"] }
tokio = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
